# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prof.º Marco Antonio Andrade
email: marco.andrade at ifro.edu.br
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcoandra.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcoaugustoandrade
github_username:  marcoaugustoandrade

# Buscando as páginas no diretório _pages
include: ['_pages']

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Algolia
algolia:
  application_id: '2GHCE399VU'
  index_name: 'dev_MARCO'

# SASS
sass:
  style: compressed
  sass_dir: _sass

# Arquivos que não serão rendendirados para _site
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - .eslintrc.json
  - .editorconfig
  - Gemfile
  - Gemfile.lock
